//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Adjustment
    {
        public int AdjustmentID { get; set; }
        public int AdjusterID { get; set; }
        public int ClaimID { get; set; }
        public bool Gutters { get; set; }
        public bool Exterior { get; set; }
        public bool Interior { get; set; }
        public int AdjustmentResultID { get; set; }
        public System.DateTime AdjustmentDate { get; set; }
        public string AdjustmentComment { get; set; }
    
        public virtual Adjuster Adjuster { get; set; }
        public virtual LU_AdjustmentResults LU_AdjustmentResults { get; set; }
        public virtual Claim Claim { get; set; }
    }
}
