//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarData
    {
        public int EntryID { get; set; }
        public int AppointmentTypeID { get; set; }
        public int EmployeeID { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
        public Nullable<int> ClaimID { get; set; }
        public Nullable<int> LeadID { get; set; }
        public string Note { get; set; }
    
        public virtual LU_AppointmentTypes LU_AppointmentTypes { get; set; }
        public virtual Claim Claim { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Lead Lead { get; set; }
    }
}
