//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimStatus
    {
        public int ClaimStatusID { get; set; }
        public int ClaimID { get; set; }
        public int ClaimStatusTypeID { get; set; }
        public System.DateTime ClaimStatusDate { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual LU_ClaimStatusTypes LU_ClaimStatusTypes { get; set; }
    }
}
