//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimVendor
    {
        public int ClaimID { get; set; }
        public int VendorID { get; set; }
        public int ServiceTypeID { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual LU_ServiceTypes LU_ServiceTypes { get; set; }
        public virtual Vendor Vendor { get; set; }
    }
}
