//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClaimDocument
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ClaimDocument()
        {
            this.Damages = new HashSet<Damage>();
        }
    
        public int DocumentID { get; set; }
        public int ClaimID { get; set; }
        public string FilePath { get; set; }
        public string FileName { get; set; }
        public string FileExt { get; set; }
        public int DocTypeID { get; set; }
        public System.DateTime DocumentDate { get; set; }
        public string SignatureImagePath { get; set; }
        public Nullable<int> NumSignatures { get; set; }
        public string InitialImagePath { get; set; }
        public Nullable<int> NumInitials { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual LU_ClaimDocumentTypes LU_ClaimDocumentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage> Damages { get; set; }
    }
}
