//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Damage
    {
        public int DamageID { get; set; }
        public int PlaneID { get; set; }
        public int DamageTypeID { get; set; }
        public int DocumentID { get; set; }
        public int DamageMeasurement { get; set; }
        public int xCoordinate { get; set; }
        public int yCoordinate { get; set; }
    
        public virtual ClaimDocument ClaimDocument { get; set; }
        public virtual LU_DamageTypes LU_DamageTypes { get; set; }
        public virtual Plane Plane { get; set; }
    }
}
