//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeDetail
    {
        public int EmployeeDetailsID { get; set; }
        public int EmployeeID { get; set; }
        public string MailingAddress { get; set; }
        public string Zip { get; set; }
        public System.DateTime DateHired { get; set; }
        public Nullable<System.DateTime> DateReleased { get; set; }
        public string ShirtSize { get; set; }
        public Nullable<double> PayRate { get; set; }
        public Nullable<int> PayTypeID { get; set; }
        public Nullable<int> PayFrequencyID { get; set; }
        public bool PreviousEmployee { get; set; }
        public string DLPhotoPath { get; set; }
        public string CompanyPhotoPath { get; set; }
        public string SignaturePath { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LU_PayFrequencies LU_PayFrequencies { get; set; }
        public virtual LU_PayTypes LU_PayTypes { get; set; }
    }
}
