//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inspection
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inspection()
        {
            this.Planes = new HashSet<Plane>();
        }
    
        public int InspectionID { get; set; }
        public int ClaimID { get; set; }
        public int RidgeMaterialTypeID { get; set; }
        public int ShingleTypeID { get; set; }
        public System.DateTime InspectionDate { get; set; }
        public bool SkyLights { get; set; }
        public bool Leaks { get; set; }
        public bool GutterDamage { get; set; }
        public bool DrivewayDamage { get; set; }
        public bool MagneticRollers { get; set; }
        public bool IceWaterShield { get; set; }
        public bool EmergencyRepair { get; set; }
        public Nullable<double> EmergencyRepairAmount { get; set; }
        public bool QualityControl { get; set; }
        public bool ProtectLandscaping { get; set; }
        public bool RemoveTrash { get; set; }
        public bool FurnishPermit { get; set; }
        public bool CoverPool { get; set; }
        public bool InteriorDamage { get; set; }
        public bool ExteriorDamage { get; set; }
        public bool LightningProtection { get; set; }
        public bool TearOff { get; set; }
        public bool Satellite { get; set; }
        public bool SolarPanels { get; set; }
        public int RoofAge { get; set; }
        public string Comments { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual LU_RidgeMaterialTypes LU_RidgeMaterialTypes { get; set; }
        public virtual LU_ShingleTypes LU_ShingleTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Plane> Planes { get; set; }
    }
}
