//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class InsuranceCompany
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InsuranceCompany()
        {
            this.Adjusters = new HashSet<Adjuster>();
            this.Claims = new HashSet<Claim>();
        }
    
        public int InsuranceCompanyID { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string Zip { get; set; }
        public string ClaimPhoneNumber { get; set; }
        public string ClaimPhoneExt { get; set; }
        public string FaxNumber { get; set; }
        public string FaxExt { get; set; }
        public string Email { get; set; }
        public bool Independent { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Adjuster> Adjusters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Claim> Claims { get; set; }
    }
}
