//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderItem
    {
        public int OrderItemID { get; set; }
        public int OrderID { get; set; }
        public int ProductID { get; set; }
        public int UnitOfMeasureID { get; set; }
        public int Quantity { get; set; }
    
        public virtual LU_Products LU_Products { get; set; }
        public virtual LU_UnitOfMeasures LU_UnitOfMeasures { get; set; }
        public virtual Order Order { get; set; }
    }
}
