//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int PaymentID { get; set; }
        public int ClaimID { get; set; }
        public int PaymentTypeID { get; set; }
        public int PaymentDescriptionID { get; set; }
        public double Amount { get; set; }
        public System.DateTime PaymentDate { get; set; }
    
        public virtual Claim Claim { get; set; }
        public virtual LU_PaymentDescriptions LU_PaymentDescriptions { get; set; }
        public virtual LU_PaymentTypes LU_PaymentTypes { get; set; }
    }
}
