//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Plane
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Plane()
        {
            this.Damages = new HashSet<Damage>();
        }
    
        public int PlaneID { get; set; }
        public int PlaneTypeID { get; set; }
        public int InspectionID { get; set; }
        public int GroupNumber { get; set; }
        public Nullable<int> NumOfLayers { get; set; }
        public Nullable<int> ThreeAndOne { get; set; }
        public Nullable<int> FourAndUp { get; set; }
        public Nullable<int> Pitch { get; set; }
        public Nullable<int> HipValley { get; set; }
        public Nullable<int> RidgeLength { get; set; }
        public Nullable<int> RakeLength { get; set; }
        public Nullable<int> EaveHeight { get; set; }
        public Nullable<int> EaveLength { get; set; }
        public Nullable<int> NumberDecking { get; set; }
        public Nullable<int> StepFlashing { get; set; }
        public Nullable<double> SquareFootage { get; set; }
        public string ItemSpec { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Damage> Damages { get; set; }
        public virtual Inspection Inspection { get; set; }
        public virtual LU_PlaneTypes LU_PlaneTypes { get; set; }
    }
}
