//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public int EmployeeID { get; set; }
        public string Username { get; set; }
        public string Pass { get; set; }
        public int PermissionID { get; set; }
        public bool Active { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual LU_Permissions LU_Permissions { get; set; }
    }
}
