//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRNNexus_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vendor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vendor()
        {
            this.ClaimVendors = new HashSet<ClaimVendor>();
            this.Invoices = new HashSet<Invoice>();
            this.LU_Products = new HashSet<LU_Products>();
            this.Orders = new HashSet<Order>();
        }
    
        public int VendorID { get; set; }
        public int VendorTypeID { get; set; }
        public string CompanyName { get; set; }
        public string EIN { get; set; }
        public string ContactFirstName { get; set; }
        public string ContactLastName { get; set; }
        public string Suffix { get; set; }
        public string VendorAddress { get; set; }
        public string Zip { get; set; }
        public string Phone { get; set; }
        public string CompanyPhone { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Website { get; set; }
        public Nullable<System.DateTime> GeneralLiabilityExpiration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClaimVendor> ClaimVendors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<LU_Products> LU_Products { get; set; }
        public virtual LU_VendorTypes LU_VendorTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order> Orders { get; set; }
    }
}
